[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
spoke_lending = "SPoKELendvz7Qh3rXjSJQnAECH5fYCFoML4gnc4L6SY"

[programs.devnet]
spoke_lending = "SPoKELendvz7Qh3rXjSJQnAECH5fYCFoML4gnc4L6SY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
